---
- name: copy tomcat-user file into ansible node side
  template:
     src: templates/mytomuser.j2
     dest: /opt/tomcat/conf/tomcat-users.xml 

- name: copy contex file into node side
  template:
     src: templates/mytomcontex.j2
     dest: /opt/tomcat/webapps/manager/META-INF/context.xml


- name: copy host context file into node side
  template: 
     src: templates/myhostman.j2
     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml

- name: create a tomcat service into node side
  template:
     src: templates/tomservice.j2
     dest: /etc/systemd/system/tomcat.service
     